### ISSUE TITLE
Bug: Can't write large rds files to S3

### ISSUE THREAD

**Issue by JanLauGe** [cloudyr/aws.s3#332] opened 2020-01-16 14:51 UTC
As per title, `s3write_using(FUN = write_rds)` doesn't work for large files. I assume this is also true for other large file paths as it seems to be a problem with the `sprintf` function and large integers.

Reproducible example:
(You will need an S3 bucket to run all of it)
```R
library(tidyverse)
library(aws.s3)
library(nycflights13)

# make a big df
df <- map_dfr(1:50, ~flights)
# check dimensions (should be almost 320 MM entries)
dim(df)[1] * dim(df)[2] / 1000000

s3write_using(
  x = df,
  FUN = write_rds, 
  object = 'some/s3/file_path.rds', 
  bucket = 'my_s3_bucket')
```

This produces the following error:
```
Error in sprintf("File size is %d. Consider setting 'multipart = TRUE'.",  : 
  invalid format '%d'; use format %f, %e, %g or %a for numeric objects

> traceback()
4: sprintf("File size is %d. Consider setting 'multipart = TRUE'.", 
       headers[["Content-Length"]])
3: message(sprintf("File size is %d. Consider setting 'multipart = TRUE'.", 
       headers[["Content-Length"]]))
2: put_object(file = tmp, bucket = bucket, object = object)
1: s3write_using(x = df, FUN = write_rds, object = "some/s3/file_path.rds", 
       bucket = "my_s3_bucket")
```

I think this should be fixable by simply switching the parameter in the message function. Thoughts?

**Comment by s-u** [comment] 2020-03-12 04:00
Thanks. Please check the latest version, this is a duplicate of #329 which is now fixed. Please re-open if there is another problem triggered by that example.

**Closed by s-u** 2020-03-12 04:00 UTC
