### ISSUE TITLE
Feature request: ability to add a file to a bucket given the raw file contents

### ISSUE THREAD

**Issue by daattali** [cloudyr/aws.s3#103] opened 2017-01-15 05:36 UTC
For example, suppose I have a data frame I want to upload (as a csv). I don't want to have to save the file to disk first (so that rules out `save_object()`) and I don't want it to be an RDS object, I just want to upload a string and be able to load it later and read.csv() it into a dataframe.

For example, `data.frame(col1="val1", col2="val2")` can be saved as a text file that contains `"col1,col2\nval1,val2"`, and that text can be read as `read.csv(text = ...)` to reproduce the dataframe.

I couldn't find any save/put function that was able to upload an object like that

**Comment by leeper** [comment] 2017-01-15 10:52
Duplicate of #99

**Closed by leeper** 2017-01-15 10:52 UTC
Labels: enhancement
