### ISSUE TITLE
Avoid region prefix on hostname for non-Amazon endpoints

### ISSUE THREAD

**Issue by lawremi** [cloudyr/aws.s3#318] opened 2019-10-11 19:31 UTC
For non-Amazon endpoints (environment configured appropriately) and version 0.3.20 (from GitHub), 
```R
library(aws.s3)
bucket <- get_bucket("foo")
```
fails with an "unknown host" error, with the hostname pattern "us-east-1.blah.blah.com". 

Our internal (NetApp-based) S3 implementation does not support prefixing the hostname with the region, and there's reason to expect that it would. What about supporting a global option for disabling that behavior? I've made that change locally and everything works as expected.

**Comment by raymondben** [comment] 2019-10-15 06:55
I think the problem lies upstream in `aws.signature::locate_credentials` (which is called internally by `aws.s3::s3HTTP`). Calling `aws.signature::locate_credentials(region = "")` should presumably return an empty string for `region`, but instead it defaults to "us-east-1".

**Comment by raymondben** [comment] 2019-10-15 07:09
See https://github.com/cloudyr/aws.signature/issues/44 for the issue in aws.signature, otherwise if it needs to be fixed in aws.s3 then perhaps override the region value at https://github.com/cloudyr/aws.s3/blob/master/R/s3HTTP.R#L60, e.g.:
`if (!identical(region, "")) region <- credentials[["region"]]`

**Comment by lawremi** [comment] 2019-10-15 12:13
Are you sure it's OK to prefix the the region onto the hostname across all S3 implementations? I'm not sure that's part of any spec.

**Comment by s-u** [comment] 2020-03-12 04:03
I have added a work-around here - see #340 which is a duplicate of this, now fixed - which explicitly ignores the result from `aws.signature`, but I agree that, ideally, this should be addressed in `aws.signature`.

**Closed by s-u** 2020-03-12 04:03 UTC
