### ISSUE TITLE
Provide a way to access S3 via AWS IAM roles

### ISSUE THREAD

**Issue by rgbkrk** [cloudyr/aws.s3#65] opened 2016-08-23 00:22 UTC
I'd like a way to do S3 access without the secret and key, [relying on instance roles](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html).

Approach:
- Fetch http://169.254.169.254/latest/meta-data/iam/security-credentials/
- If successful, returns a role name

```
$ curl http://169.254.169.254/latest/meta-data/iam/security-credentials/
myrole
```
- Fetch http://169.254.169.254/latest/meta-data/iam/security-credentials/NAME
- Response (if successful), is a JSON object with the key, secret, _and_ a token

``` json
{
  "Code" : "Success",
  "LastUpdated" : "2016-08-22T23:42:03Z",
  "Type" : "AWS-HMAC",
  "AccessKeyId" : "",
  "SecretAccessKey" : "",
  "Token" : "",
  "Expiration" : "2016-08-23T06:06:28Z"
}
```

The token is _definitely_ required here -- you can't just use the secret and key. Since the tokens expire, you tend to query for a new token some time before the expiration.

**Comment by rgbkrk** [comment] 2016-08-23 00:23
Somewhat of a subissue then: if this library accepted the token I could do the other part of the handshake separately.

**Comment by leeper** [comment] 2016-08-23 06:47
So, I think you can do this already. You just have to set your credentials as usual to the temporary values returned by the role request and then specify a `X-Amz-Security-Token` header equal to the token for each request.

**Comment by rgbkrk** [comment] 2016-08-23 15:54
Is there some way in this lib to overwrite the header on the fly or do you want me to make a PR?

**Comment by leeper** [comment] 2016-09-07 13:00
You can pass headers to any function. Some have an explicit `header` argument. For others, it is implicit in `...` and passed to `s3HTTP()`.

**Comment by tomsing1** [comment] 2016-10-25 01:18
This is a great feature. Perhaps you could highlight an example in the documentation / on the github landing page on how to use it?

**Comment by kadrach** [comment] 2016-11-14 04:58
Boto does this under the hood, having this in cloudyR as well would make credential handling much more consistent for us :)

**Comment by leeper** [comment] 2016-11-14 09:34
Thanks for the feedback, everyone. Would it be useful to have a function like `assume_role()`, which would query AWS for the credentials (access key, secret key, and session token) for a role and then assign those to the appropriate environment variables so that subsequent code would automatically be executed by that role? That seems to be what boto does (though I haven't used, so please correct me if I'm wrong).

**Comment by rgbkrk** [comment] 2016-11-14 15:31
It would be excellent to have a function for assuming the role.

**Comment by kadrach** [comment] 2016-11-15 06:10
@leeper I'm not well versed in the internals of boto, but it's credentials lookup is rather more complex. Being the base of the `awscli` it looks in various [config files](http://boto3.readthedocs.io/en/latest/guide/configuration.html) and falls back to IAM metadata lookup if all else fails. 

This works across the board for pretty much all IAM-enabled AWS services (e.g. S3 access, or EC2 permissions, or SQS, etc). This almost completely removes the need for credentials when working inside AWS.

I'm not sure if boto caches these credentials (probably?). Any solution that removes the need to handle credentials would be a great feature!

**Comment by drknexus** [comment] 2016-11-19 18:15
Boto has a pretty replete set of fallbacks: http://boto3.readthedocs.io/en/latest/guide/configuration.html

In order:
1. Passing credentials as parameters in the boto.client() method
1. Passing credentials as parameters when creating a Session object
1. Environment variables
1. Shared credential file (~/.aws/credentials)
1. AWS config file (~/.aws/config)
1. Assume Role provider
1. Boto2 config file (/etc/boto.cfg and ~/.boto)
1. Instance metadata service on an Amazon EC2 instance that has an IAM role configured.

**Comment by leeper** [comment] 2016-11-21 09:57
Quick update, I've done the following:

 1. The [aws.signature](https://github.com/cloudyr/aws.signature) package (dev on GitHub) now offers a `session_token` argument, which will be incorporated into signatures, drawing by default from the `AWS_SESSION_TOKEN` variable. This will also automatically be added to the request headers.
 2. The [aws.iam](https://github.com/cloudyr/aws.iam) package should provide functionality for working with roles, keys, etc. There is experimental functionality on the [sts](https://github.com/cloudyr/aws.iam/tree/sts) branch for doing the kind of "AssumeRole" behavior we've been discussing here. Basically, the way I've conceptualized it, you call `assume_role()`, any existing credentials are cached, environment variables are overwritten with the new temporary credentials, and then you can restore the originals using `restore_credentials()`. Not sure this is the best way, but it seems to make the most sense. Please supply feedback if you get a chance.
 3. The [`session_token` branch of this package repo](https://github.com/cloudyr/aws.s3/tree/session_token) adds support for session tokens via the aforementioned environment variable. This is untested, though, so please let me know if you run into trouble with it. (You'll need the dev version of aws.signature for that functionality.)

**Comment by kadrach** [comment] 2016-12-19 04:48
Hi @leeper, I'm afraid I don't understand this implementation. 

Using the boto3-based aws command line:
```
aws --debug s3 ls s3://my_bucket/
```
this happens (abbreviated):
<pre>
$ aws --debug s3 ls s3://my_bucket/
2016-12-19 04:35:31,640 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.11.10 Python/2.7.5 Linux/3.10.0-327.10.1.el7.x86_64 botocore/1.4.67
2016-12-19 04:35:31,640 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--debug', 's3', 'ls', 's3://my_bucket/']
...
2016-12-19 04:35:31,643 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2016-12-19 04:35:31,643 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2016-12-19 04:35:31,644 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2016-12-19 04:35:31,644 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: config-file
2016-12-19 04:35:31,644 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: ec2-credentials-file
2016-12-19 04:35:31,644 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: boto-config
2016-12-19 04:35:31,644 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: container-role
<b>2016-12-19 04:35:31,644 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: iam-role</b>
2016-12-19 04:35:31,651 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): 169.254.169.254
2016-12-19 04:35:31,652 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "GET /latest/meta-data/iam/security-credentials/ HTTP/1.1" 200 29
2016-12-19 04:35:31,654 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): 169.254.169.254
<b>2016-12-19 04:35:31,655 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "GET /latest/meta-data/iam/security-credentials/my_role HTTP/1.1" 200 894 </b>
<b>2016-12-19 04:35:31,655 - MainThread - botocore.credentials - INFO - Found credentials from IAM Role: my_role</b>
...
2016-12-19 04:35:31,720 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=ListObjects) (verify_ssl=True) with params: {'body': '', 'url': u'https://s3.amazonaws.com/my_bucket?delimiter=%2F&prefix=&encoding-type=url', 'headers': {'User-Agent': 'aws-cli/1.11.10 Python/2.7.5 Linux/3.10.0-327.10.1.el7.x86_64 botocore/1.4.67'}, 'context': {'encoding_type_auto_set': True, 'client_region': u'us-east-1', 'signing': {'bucket': u'my_bucket'}, 'has_streaming_input': False, 'client_config': <botocore.config.Config object at 0x2643650>}, 'query_string': {u'delimiter': '/', u'prefix': u'', u'encoding-type': 'url'}, 'url_path': u'/my_bucket', 'method': u'GET'}
2016-12-19 04:35:31,720 - MainThread - botocore.hooks - DEBUG - Event request-created.s3.ListObjects: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x26435d0>>
2016-12-19 04:35:31,720 - MainThread - botocore.hooks - DEBUG - Event before-sign.s3.ListObjects: calling handler <function fix_s3_host at 0x1393320>
2016-12-19 04:35:31,720 - MainThread - botocore.utils - DEBUG - Checking for DNS compatible bucket for: https://s3.amazonaws.com/my_bucket?delimiter=%2F&prefix=&encoding-type=url
2016-12-19 04:35:31,720 - MainThread - botocore.utils - DEBUG - URI updated to: https://my_bucket.s3.amazonaws.com/?delimiter=%2F&prefix=&encoding-type=url
<b>2016-12-19 04:35:31,721 - MainThread - botocore.auth - DEBUG - Calculating signature using hmacv1 auth.</b>
2016-12-19 04:35:31,721 - MainThread - botocore.auth - DEBUG - HTTP request method: GET
...
</pre>

This instance has the iam instance profile `my_role` attached to it, and the only effect of this policy/role is to allow access to `my_bucket`. This is the behaviour I was expecting to reproduce (possibly specifying the role name itself if necessary), but have not been able to.

Are you able to provide an example?

**Comment by leeper** [comment] 2016-12-19 10:23
Ah, okay, sorry, I misunderstood the intention here (I was thinking about assuming a role on a local machine rather than on an EC2 instance). This should be possible but it's not setup yet. I've opened an issue for it here: https://github.com/cloudyr/aws.signature/issues/11

**Comment by leeper** [comment] 2017-04-23 13:34
I'm closing this here, as all of this will be handled in aws.signature; discussion continued at https://github.com/cloudyr/aws.signature/issues/11

**Closed by leeper** 2017-04-23 13:34 UTC
Labels: documentation, enhancement
