### ISSUE TITLE
Read .gz file from s3

### ISSUE THREAD

**Issue by xie67** [cloudyr/aws.s3#117] opened 2017-03-06 20:32 UTC
I've used get_object to get a gz file into raw vector. However, when I used memDecompress, it showed internal error. Is there any solutions?

The code is following:
x.gz <- get_object("XXXXX.gz",bucket="XXXXX")
x <- memDecompress(x.gz,"gizp")

**Comment by leeper** [comment] 2017-03-07 16:47
Can you make a fully reproducible example for me (e.g., use a built-in R dataset, upload the gzip'd object using `put_object()` and then show the corresponding error using `get_object()`)? Thanks.

**Comment by xie67** [comment] 2017-03-08 14:58
It will be like this. Could you give me some suggestions? I am not good at using R.
> put_object(file = "video_events_feed_20170219161605_part_0.gz", object = "video_events_feed_20170219161605_part_0.gz", bucket = "tsymedia")
[1] TRUE
> x.gz <- get_object("video_events_feed_20170219161605_part_0.gz", bucket = "tsymedia")
> x <- memDecompress(x.gz, "gzip", asChar = TRUE)
Error in memDecompress(x.gz, "gzip", asChar = TRUE) :
  internal error -3 in memDecompress(2)
>

**Comment by leeper** [comment] 2017-04-22 21:47
Duplicate of https://github.com/cloudyr/aws.s3/issues/59

**Closed by leeper** 2017-04-22 21:47 UTC
Labels: duplicate, question
