### ISSUE TITLE
Unable to deploy Shiny app on shinyapps.io when using aws.s3 package

### ISSUE THREAD

**Issue by greysunil** [cloudyr/aws.s3#114] opened 2017-02-27 00:27 UTC
Preparing to deploy document...DONE
Uploading bundle for document: 159543...Error: Unable to retrieve package records for the following packages:
- "aws.s3"
Execution halted

**Comment by leeper** [comment] 2017-02-27 07:11
Do you have a question?

**Comment by greysunil** [comment] 2017-02-27 07:15
Yes. I am Unable to deploy Shiny app on shinyapps.io when using aws.s3 package. Can you please help me? This is what the output shows when I am trying to deploy my shiny app:

*Preparing to deploy document...DONE
Uploading bundle for document: 159543...Error: Unable to retrieve package records for the following packages:

"aws.s3"
Execution halted*

Even though my app works locally.

**Comment by leeper** [comment] 2017-02-27 08:44
This is a duplicate of #113

**Closed by leeper** 2017-02-27 08:44 UTC

**Comment by leeper** [comment] 2017-02-27 08:46
You can reinstall the package using devtools then try to deploy again. If that doesn't work, the issue is with shiny, so I would suggest reporting the problem there.

**Comment by greysunil** [comment] 2017-02-27 08:50
Thanks.
